@Restaurant.API_HostAddress = http://localhost:5055

GET {{Restaurant.API_HostAddress}}/weatherforecast/
Accept: application/json

###
Get {{Restaurant.API_HostAddress}}//api/restaurants

###

GET {{Restaurant.API_HostAddress}}/api/restaurants

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/2005

###

@id=0
GET {{Restaurant.API_HostAddress}}/api/restaurants/{{id}}

###
POST {{Restaurant.API_HostAddress}}/api/restaurants
Contect-Type:application/json

{
    "Name":"Tasty Kabb",
    "Description":"short for Kentucky Fried Chicken) is an American fast food restaurant chain headquartered in Louisville, Kentucky, that specializes in fried chicken.",
    "Category": "Fast Food",
    "HasDelivery": true,
    "City": "New York",
    "Street": "123 main street",
    "PostalCode": "10-010",

}