@Restaurant.API_HostAddress = http://localhost:5055

GET {{Restaurant.API_HostAddress}}/weatherforecast/
Accept: application/json

###
Get {{Restaurant.API_HostAddress}}//api/restaurants

###

GET {{Restaurant.API_HostAddress}}/api/restaurants

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/1

###

@id=0
GET {{Restaurant.API_HostAddress}}/api/restaurants/{{id}}

###
